kcrash: Autospec creation for update from version 5.71.0 to version 5.73.0
Andreas Cord-Landwehr (3):
      Convert license statements to SPDX
      Add license texts as required by REUSE specification
      State copyright information correctly according to FLA

Friedrich W. H. Kossebau (1):
      Use KF-standardized Qt logging categories

Jiří Paleček (3):
      Add missing declaration of environ, otherwise available only on GNU
      Fix undefined reference to environ by a small hack
      Don't use execvpe

Laurent Montel (1):
      Use camelcase include. (scripted)

l10n daemon script (4):
      GIT_SILENT Upgrade KF5 version to 5.72.0.
      GIT_SILENT Upgrade ECM and KF5 version requirements for 5.72.0 release.
      GIT_SILENT Upgrade KF5 version to 5.73.0.
      GIT_SILENT Upgrade ECM and KF5 version requirements for 5.73.0 release.